export const ROUTE_PATHS = {
  root: '/',
  login: '/login',
  forgotPassword: '/forgot-password',
  changePassword: '/change-password',
  pageNotFound: '/pageNotFound',

  dashboard: '/dashboard',
  users: '/users',
  roles: '/roles',
  rolesManage: '/roles/manage',
  roleUsers: '/roles/users',
  permissions: '/permissions',
  departments: '/departments',

  documents: '/documents',
  assignListView: '/assign/list-view',
  assignFolderView: '/assign/folder-view',
  documentsListView: '/documents/list-view',
  documentsFolderView: '/documents/folder-view',
  categories: '/categories',
  documentsDeepSearch: '/documents/deep-search',
  aiDocumentGenerator: '/ai-document-generator',
  aiDocumentGeneratorList: '/ai-document-generator-list',
  aiPromptTemplate: '/aiprompttemplate',
  documentsOcrContentExtractor: '/documents/ocr_content_extractor',
  bulkDocumentUpload: '/bulk-document-upload',
  fileRequest: '/file-request',
  documentAuditTrails: '/document-audit-trails',
  recentActivity: '/recent-activity',
  archiveDocuments: '/archive-documents',
  archiveFolders: '/archive-folders',
  archiveRetentionPeriod: '/archive-retention-period',
  documentStatus: '/document-status',

  capa: '/capa',
  ncr: '/ncr',
  audits: '/audits',
  reports: '/reports',
  loginAudit: '/login-audit',
  logs: '/logs',

  courseList: '/course/list',
  lmsContent: '/lms/content',
  lmsAssignments: '/lms/assignments',
  lmsChecking: '/lms/checking',
  lmsTestSeries: '/lms/test-series',
  lmsTestSeriesBuilder: '/lms/test-series/:testSeriesId/builder',
  courseMyCourses: '/course/my-courses',
  trainingMyCoursePlayer: '/training/my-courses/:courseId',
  trainingTestPlayer: '/training/test/:testSeriesId',
  courseAssign: '/course/assign',
  courseSummary: '/course/summary',

  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsSmtp: '/settings/smtp',
  settingsStorage: '/settings/storage',
  settingsCompanyProfile: '/settings/company-profile',
} as const;
