import {
  ArticleIcon,
  BellIcon,
  BuildIcon,
  ClipboardIcon,
  DashboardIcon,
  ErrorIcon,
  FeedbackIcon,
  FolderSharedIcon,
  ListIcon,
  MergeIcon,
  RepeatIcon,
  SchoolIcon,
  SettingsIcon,
  ShieldIcon,
  TruckIcon,
  WarningIcon,
} from "./icons";
import { NavSection } from "./types";

export const navSections: NavSection[] = [
  {
    title: "Main",
    items: [
      { label: "Dashboard", to: "/dashboard", icon: DashboardIcon },
      {
        label: "Audit",
        icon: ClipboardIcon,
        children: [
          { label: "Audit List", to: "/audit/audit-list" },
          { label: "Audit for Review", to: "/audit/audit-for-review" },
          { label: "Manage Audit Template", to: "/audit/audit-template" },
          { label: "Department", to: "/department" },
          { label: "Audit Logs", to: "/audit/logs" },
        ],
      },
      {
        label: "CAPA",
        icon: ShieldIcon,
        children: [
          { label: "CAPA Request", to: "/capa/requests" },
          { label: "Root Cause Methodology", to: "/capa/root-cause-methodology" },
          { label: "CAPA Request Logs", to: "/capa/request/logs" },
          { label: "My CAPA Actions", to: "/capa/actions" },
        ],
      },
      {
        label: "Non Conformance",
        icon: ErrorIcon,
        children: [
          { label: "List", to: "/nc/conformances" },
          { label: "Add New", to: "/nc/conformance/manage" },
          { label: "Non Conformance Logs", to: "/nc/conformance/logs" },
          { label: "Response Type", to: "/nc/conformance/response/type" },
        ],
      },
      {
        label: "Complaint",
        icon: FeedbackIcon,
        children: [
          { label: "List", to: "/complaint/list" },
          { label: "Add New", to: "/complaint/manage" },
          { label: "Complaint Type", to: "/complaint/types" },
          { label: "Complaint Logs", to: "/complaint/logs" },
          { label: "My Complaints", to: "/complaint/actions" },
        ],
      },
      {
        label: "Risk Management",
        icon: WarningIcon,
        children: [
          { label: "List", to: "/risk/list" },
          { label: "Add New", to: "/risk/manage" },
          { label: "Risk Category", to: "/risk/categories" },
          { label: "Risk Logs", to: "/risk/logs" },
          { label: "My Risks", to: "/risk/my-risk-list" },
        ],
      },
      {
        label: "4M Change",
        icon: BuildIcon,
        children: [
          { label: "Change Request List", to: "/4m-change/list" },
          { label: "Create Change Request", to: "/4m-change/manage" },
          { label: "Category Setup", to: "/4m-change/categories" },
          { label: "Approval Workflow", to: "/4m-change/workflow" },
          { label: "Risk Assessment", to: "/4m-change/risk-assessment" },
          { label: "Validation Plan", to: "/4m-change/validation" },
          { label: "Implementation Tracker", to: "/4m-change/implementation" },
          { label: "My Change Actions", to: "/4m-change/actions" },
          { label: "Change Logs", to: "/4m-change/logs" },
          { label: "Reports", to: "/4m-change/reports" },
        ],
      },
      {
        label: "Supplier",
        icon: TruckIcon,
        children: [
          { label: "List", to: "/supplier/list" },
          { label: "Add New", to: "/supplier/manage" },
        ],
      },
      {
        label: "Training",
        icon: SchoolIcon,
        children: [
          { label: "Course", to: "/course/list" },
          { label: "My Courses", to: "/course/my-courses" },
          { label: "Assign Course", to: "/course/assign" },
          { label: "Course Summary", to: "/course/summary" },
        ],
      },
      {
        label: "Document Management",
        icon: ArticleIcon,
        children: [
          { label: "My Document View", to: "/assign/list-view" },
          { label: "My Folder View", to: "/assign/folder-view" },
          { label: "All Document View", to: "/documents/list-view" },
          { label: "All Folder View", to: "/documents/folder-view" },
          { label: "Folders", to: "/categories" },
          { label: "Deep Search", to: "/documents/deep-search" },
          { label: "AI Document Generator", to: "/ai-document-generator" },
          { label: "AI Generator List", to: "/ai-document-generator-list" },
          { label: "AI Prompt Templates", to: "/aiprompttemplate" },
          { label: "OCR Content Extractor", to: "/documents/ocr_content_extractor" },
          { label: "Bulk Document Upload", to: "/bulk-document-upload" },
          { label: "File Request Link", to: "/file-request" },
          { label: "Documents Audit Trail", to: "/document-audit-trails" },
          { label: "Recent Activity", to: "/recent-activity" },
          { label: "Archive Documents", to: "/archive-documents" },
          { label: "Archive Folders", to: "/archive-folders" },
          { label: "Archive Retention Period", to: "/archive-retention-period" },
          { label: "Document Status", to: "/document-status" },
        ],
      },
      {
        label: "Workflows",
        icon: RepeatIcon,
        children: [
          { label: "Workflow Setup Settings", to: "/workflow-settings" },
          { label: "All Workflows", to: "/workflows" },
          { label: "Request Doc via Workflow", to: "/request_document_through_workflow" },
          { label: "Workflow Logs", to: "/workflowlogs" },
        ],
      },
      { label: "My Workflows", to: "/current-workflow", icon: MergeIcon },
      { label: "Reminder", to: "/reminders", icon: BellIcon },
      { label: "Clients", to: "/client", icon: FolderSharedIcon },
      {
        label: "Access Control",
        icon: ShieldIcon,
        children: [
          { label: "Roles", to: "/roles", requiredPermissions: ["roles.read"] },
          { label: "Users", to: "/users", requiredPermissions: ["users.read"] },
          { label: "Role User", to: "/roles/users", requiredPermissions: ["users.read", "roles.read"] },
        ],
      },
      {
        label: "Settings",
        icon: SettingsIcon,
        children: [
          { label: "Email SMTP Settings", to: "/settings/smtp", requiredPermissions: ["settings.read"] },
          { label: "General Settings", to: "/settings", requiredPermissions: ["settings.read"] },
          { label: "Storage Settings", to: "/settings/storage", requiredPermissions: ["settings.read"] },
          { label: "Company Profile", to: "/settings/company-profile", requiredPermissions: ["settings.read"] },
        ],
      },
      {
        label: "Logs",
        icon: ListIcon,
        children: [
          { label: "Login Audits", to: "/login-audit" },
          { label: "Error Logs", to: "/logs" },
        ],
      },
    ],
  },
];
