import {
  ArticleIcon,
  BellIcon,
  BuildIcon,
  ClipboardIcon,
  DashboardIcon,
  ErrorIcon,
  FeedbackIcon,
  FolderSharedIcon,
  ListIcon,
  MergeIcon,
  RepeatIcon,
  SchoolIcon,
  SettingsIcon,
  ShieldIcon,
  TruckIcon,
  WarningIcon,
} from "./icons";
import { NavSection } from "./types";

export const navSections: NavSection[] = [
  {
    title: "Main",
    items: [
      { label: "Dashboard", to: "/dashboard", icon: DashboardIcon, requiredPermissions: ["dashboard.read"] },
      {
        label: "Audit",
        icon: ClipboardIcon,
        requiredPermissions: ["audits.read"],
        children: [
          { label: "Audit List", to: "/audit/audit-list", requiredPermissions: ["audits.read"] },
          { label: "Audit for Review", to: "/audit/audit-for-review", requiredPermissions: ["audits.read"] },
          { label: "Manage Audit Template", to: "/audit/audit-template", requiredPermissions: ["audits.write"] },
          { label: "Department", to: "/department", requiredPermissions: ["departments.read"] },
          { label: "Audit Logs", to: "/audit/logs", requiredPermissions: ["audits.read"] },
        ],
      },
      {
        label: "CAPA",
        icon: ShieldIcon,
        requiredPermissions: ["capa.read"],
        children: [
          { label: "CAPA Request", to: "/capa/requests", requiredPermissions: ["capa.read"] },
          { label: "Root Cause Methodology", to: "/capa/root-cause-methodology", requiredPermissions: ["capa.write"] },
          { label: "CAPA Request Logs", to: "/capa/request/logs", requiredPermissions: ["capa.read"] },
          { label: "My CAPA Actions", to: "/capa/actions", requiredPermissions: ["capa.read"] },
        ],
      },
      {
        label: "Non Conformance",
        icon: ErrorIcon,
        requiredPermissions: ["ncr.read"],
        children: [
          { label: "List", to: "/nc/conformances", requiredPermissions: ["ncr.read"] },
          { label: "Add New", to: "/nc/conformance/manage", requiredPermissions: ["ncr.write"] },
          { label: "Non Conformance Logs", to: "/nc/conformance/logs", requiredPermissions: ["ncr.read"] },
          { label: "Response Type", to: "/nc/conformance/response/type", requiredPermissions: ["ncr.write"] },
        ],
      },
      {
        label: "Complaint",
        icon: FeedbackIcon,
        children: [
          { label: "List", to: "/complaint/list" },
          { label: "Add New", to: "/complaint/manage" },
          { label: "Complaint Type", to: "/complaint/types" },
          { label: "Complaint Logs", to: "/complaint/logs" },
          { label: "My Complaints", to: "/complaint/actions" },
        ],
      },
      {
        label: "Risk Management",
        icon: WarningIcon,
        children: [
          { label: "List", to: "/risk/list" },
          { label: "Add New", to: "/risk/manage" },
          { label: "Risk Category", to: "/risk/categories" },
          { label: "Risk Logs", to: "/risk/logs" },
          { label: "My Risks", to: "/risk/my-risk-list" },
        ],
      },
      {
        label: "4M Change",
        icon: BuildIcon,
        children: [
          { label: "Change Request List", to: "/4m-change/list" },
          { label: "Create Change Request", to: "/4m-change/manage" },
          { label: "Category Setup", to: "/4m-change/categories" },
          { label: "Approval Workflow", to: "/4m-change/workflow" },
          { label: "Risk Assessment", to: "/4m-change/risk-assessment" },
          { label: "Validation Plan", to: "/4m-change/validation" },
          { label: "Implementation Tracker", to: "/4m-change/implementation" },
          { label: "My Change Actions", to: "/4m-change/actions" },
          { label: "Change Logs", to: "/4m-change/logs" },
          { label: "Reports", to: "/4m-change/reports" },
        ],
      },
      {
        label: "Supplier",
        icon: TruckIcon,
        children: [
          { label: "List", to: "/supplier/list" },
          { label: "Add New", to: "/supplier/manage" },
        ],
      },
      {
        label: "Training",
        icon: SchoolIcon,
        children: [
          { label: "Course", to: "/course/list" },
          { label: "My Courses", to: "/course/my-courses" },
          { label: "Assign Course", to: "/course/assign" },
          { label: "Course Summary", to: "/course/summary" },
        ],
      },
      {
        label: "Document Management",
        icon: ArticleIcon,
        requiredPermissions: ["documents.read"],
        children: [
          { label: "My Document View", to: "/assign/list-view", requiredPermissions: ["documents.read"] },
          { label: "My Folder View", to: "/assign/folder-view", requiredPermissions: ["documents.read"] },
          { label: "All Document View", to: "/documents/list-view", requiredPermissions: ["documents.read"] },
          { label: "All Folder View", to: "/documents/folder-view", requiredPermissions: ["documents.read"] },
          { label: "Folders", to: "/categories", requiredPermissions: ["documents.read"] },
          { label: "Deep Search", to: "/documents/deep-search", requiredPermissions: ["documents.read"] },
          { label: "AI Document Generator", to: "/ai-document-generator", requiredPermissions: ["documents.write"] },
          { label: "AI Generator List", to: "/ai-document-generator-list", requiredPermissions: ["documents.read"] },
          { label: "AI Prompt Templates", to: "/aiprompttemplate", requiredPermissions: ["documents.write"] },
          { label: "OCR Content Extractor", to: "/documents/ocr_content_extractor", requiredPermissions: ["documents.write"] },
          { label: "Bulk Document Upload", to: "/bulk-document-upload", requiredPermissions: ["documents.write"] },
          { label: "File Request Link", to: "/file-request", requiredPermissions: ["documents.write"] },
          { label: "Documents Audit Trail", to: "/document-audit-trails", requiredPermissions: ["documents.read"] },
          { label: "Recent Activity", to: "/recent-activity", requiredPermissions: ["documents.read"] },
          { label: "Archive Documents", to: "/archive-documents", requiredPermissions: ["documents.read"] },
          { label: "Archive Folders", to: "/archive-folders", requiredPermissions: ["documents.read"] },
          { label: "Archive Retention Period", to: "/archive-retention-period", requiredPermissions: ["documents.write"] },
          { label: "Document Status", to: "/document-status", requiredPermissions: ["documents.read"] },
        ],
      },
      {
        label: "Workflows",
        icon: RepeatIcon,
        children: [
          { label: "Workflow Setup Settings", to: "/workflow-settings" },
          { label: "All Workflows", to: "/workflows" },
          { label: "Request Doc via Workflow", to: "/request_document_through_workflow" },
          { label: "Workflow Logs", to: "/workflowlogs" },
        ],
      },
      { label: "My Workflows", to: "/current-workflow", icon: MergeIcon, requiredPermissions: ["reports.read"] },
      { label: "Reminder", to: "/reminders", icon: BellIcon },
      { label: "Clients", to: "/client", icon: FolderSharedIcon },
      {
        label: "Access Control",
        icon: ShieldIcon,
        children: [
          { label: "Roles", to: "/roles", requiredPermissions: ["roles.read"] },
          { label: "Users", to: "/users", requiredPermissions: ["users.read"] },
          { label: "Role User", to: "/roles/users", requiredPermissions: ["users.read", "roles.read"] },
        ],
      },
      {
        label: "Settings",
        icon: SettingsIcon,
        children: [
          { label: "Email SMTP Settings", to: "/settings/smtp", requiredPermissions: ["settings.read"] },
          { label: "General Settings", to: "/settings", requiredPermissions: ["settings.read"] },
          { label: "Storage Settings", to: "/settings/storage", requiredPermissions: ["settings.read"] },
          { label: "Company Profile", to: "/settings/company-profile", requiredPermissions: ["settings.read"] },
        ],
      },
      {
        label: "Logs",
        icon: ListIcon,
        children: [
          { label: "Login Audits", to: "/login-audit", requiredPermissions: ["reports.read"] },
          { label: "Error Logs", to: "/logs", requiredPermissions: ["reports.read"] },
        ],
      },
    ],
  },
];
