import {
  ArticleIcon,
  BellIcon,
  BuildIcon,
  ClipboardIcon,
  DashboardIcon,
  ErrorIcon,
  FeedbackIcon,
  FolderSharedIcon,
  ListIcon,
  MergeIcon,
  RepeatIcon,
  SchoolIcon,
  SettingsIcon,
  ShieldIcon,
  TruckIcon,
  WarningIcon,
} from "./icons";
import { NavSection } from "./types";

export const navSections: NavSection[] = [
  {
    title: "Main",
    items: [
      { label: "Dashboard", to: "/dashboard", icon: DashboardIcon, requiredPermissions: ["VIEW_DASHBOARD"] },
      {
        label: "Audit",
        icon: ClipboardIcon,
        requiredPermissions: ["VIEW_AUDIT_LIST"],
        children: [
          { label: "Audit List", to: "/audit/audit-list", requiredPermissions: ["VIEW_AUDIT_LIST"] },
          { label: "Audit for Review", to: "/audit/audit-for-review", requiredPermissions: ["VIEW_AUDIT_REVIEW"] },
          { label: "Manage Audit Template", to: "/audit/audit-template", requiredPermissions: ["VIEW_AUDIT_TEMPLATE"] },
          { label: "Department", to: "/department", requiredPermissions: ["VIEW_DEPARTMENTS"] },
          { label: "Audit Logs", to: "/audit/logs", requiredPermissions: ["VIEW_AUDIT_LOGS"] },
        ],
      },
      {
        label: "CAPA",
        icon: ShieldIcon,
        requiredPermissions: ["VIEW_CAPA_REQUEST"],
        children: [
          { label: "CAPA Request", to: "/capa/requests", requiredPermissions: ["VIEW_CAPA_REQUEST"] },
          { label: "Root Cause Methodology", to: "/capa/root-cause-methodology", requiredPermissions: ["MANAGE_CAPA_ROOT_CAUSE_METHODLOGY"] },
          { label: "CAPA Request Logs", to: "/capa/request/logs", requiredPermissions: ["VIEW_CAPA_REQUEST_LOGS"] },
          { label: "My CAPA Actions", to: "/capa/actions", requiredPermissions: ["VIEW_MY_CAPA_ACTIONS"] },
        ],
      },
      {
        label: "Non Conformance",
        icon: ErrorIcon,
        requiredPermissions: ["VIEW_NCR_LIST"],
        children: [
          { label: "List", to: "/nc/conformances", requiredPermissions: ["VIEW_NCR_LIST"] },
          { label: "Add New", to: "/nc/conformance/manage", requiredPermissions: ["ADD_NCR"] },
          { label: "Non Conformance Logs", to: "/nc/conformance/logs", requiredPermissions: ["VIEW_NCR_LOGS"] },
          { label: "Response Type", to: "/nc/conformance/response/type", requiredPermissions: ["MANAGE_NCR_RESPONSE_TYPE"] },
        ],
      },
      {
        label: "Complaint",
        icon: FeedbackIcon,
        requiredPermissions: ["VIEW_COMPLAINT_LIST"],
        children: [
          { label: "List", to: "/complaint/list", requiredPermissions: ["VIEW_COMPLAINT_LIST"] },
          { label: "Add New", to: "/complaint/manage", requiredPermissions: ["ADD_COMPLAINT"] },
          { label: "Complaint Type", to: "/complaint/types", requiredPermissions: ["MANAGE_COMPLAINT_TYPE"] },
          { label: "Complaint Logs", to: "/complaint/logs", requiredPermissions: ["VIEW_COMPLAINT_LOGS"] },
          { label: "My Complaints", to: "/complaint/actions", requiredPermissions: ["VIEW_MY_COMPLAINTS"] },
        ],
      },
      {
        label: "Risk Management",
        icon: WarningIcon,
        requiredPermissions: ["VIEW_RISK_LIST"],
        children: [
          { label: "List", to: "/risk/list", requiredPermissions: ["VIEW_RISK_LIST"] },
          { label: "Add New", to: "/risk/manage", requiredPermissions: ["ADD_RISK"] },
          { label: "Risk Category", to: "/risk/categories", requiredPermissions: ["MANAGE_RISK_CATEGORY"] },
          { label: "Risk Logs", to: "/risk/logs", requiredPermissions: ["VIEW_RISK_LOGS"] },
          { label: "My Risks", to: "/risk/my-risk-list", requiredPermissions: ["VIEW_MY_RISKS"] },
        ],
      },
      {
        label: "4M Change",
        icon: BuildIcon,
        requiredPermissions: ["VIEW_CHANGE_REQUEST_LIST"],
        children: [
          { label: "Change Request List", to: "/4m-change/list", requiredPermissions: ["VIEW_CHANGE_REQUEST_LIST"] },
          { label: "Create Change Request", to: "/4m-change/manage", requiredPermissions: ["ADD_CHANGE_REQUEST"] },
          { label: "Category Setup", to: "/4m-change/categories", requiredPermissions: ["MANAGE_CHANGE_CATEGORY"] },
          { label: "Approval Workflow", to: "/4m-change/workflow", requiredPermissions: ["MANAGE_CHANGE_APPROVAL_WORKFLOW"] },
          { label: "Risk Assessment", to: "/4m-change/risk-assessment", requiredPermissions: ["MANAGE_CHANGE_RISK_ASSESSMENT"] },
          { label: "Validation Plan", to: "/4m-change/validation", requiredPermissions: ["MANAGE_CHANGE_VALIDATION_PLAN"] },
          { label: "Implementation Tracker", to: "/4m-change/implementation", requiredPermissions: ["VIEW_CHANGE_IMPLEMENTATION_TRACKER"] },
          { label: "My Change Actions", to: "/4m-change/actions", requiredPermissions: ["VIEW_MY_CHANGE_ACTIONS"] },
          { label: "Change Logs", to: "/4m-change/logs", requiredPermissions: ["VIEW_CHANGE_LOGS"] },
          { label: "Reports", to: "/4m-change/reports", requiredPermissions: ["VIEW_CHANGE_REPORTS"] },
        ],
      },
      {
        label: "Supplier",
        icon: TruckIcon,
        requiredPermissions: ["VIEW_SUPPLIER_LIST"],
        children: [
          { label: "List", to: "/supplier/list", requiredPermissions: ["VIEW_SUPPLIER_LIST"] },
          { label: "Add New", to: "/supplier/manage", requiredPermissions: ["ADD_SUPPLIER"] },
        ],
      },
      {
        label: "Training",
        icon: SchoolIcon,
        requiredPermissions: ["VIEW_TRAINING_COURSE"],
        children: [
          { label: "Course", to: "/course/list", requiredPermissions: ["VIEW_TRAINING_COURSE"] },
          { label: "My Courses", to: "/course/my-courses", requiredPermissions: ["VIEW_MY_COURSES"] },
          { label: "Assign Course", to: "/course/assign", requiredPermissions: ["MANAGE_TRAINING_ASSIGN_COURSE"] },
          { label: "Course Summary", to: "/course/summary", requiredPermissions: ["VIEW_COURSE_SUMMARY"] },
        ],
      },
      {
        label: "Document Management",
        icon: ArticleIcon,
        requiredPermissions: ["VIEW_MY_DOCUMENTS"],
        children: [
          { label: "My Document View", to: "/assign/list-view", requiredPermissions: ["VIEW_MY_DOCUMENTS"] },
          { label: "My Folder View", to: "/assign/folder-view", requiredPermissions: ["VIEW_MY_FOLDERS"] },
          { label: "All Document View", to: "/documents/list-view", requiredPermissions: ["VIEW_ALL_DOCUMENTS"] },
          { label: "All Folder View", to: "/documents/folder-view", requiredPermissions: ["VIEW_ALL_FOLDERS"] },
          { label: "Folders", to: "/categories", requiredPermissions: ["VIEW_DOCUMENT_FOLDERS"] },
          { label: "Deep Search", to: "/documents/deep-search", requiredPermissions: ["VIEW_DOCUMENT_DEEP_SEARCH"] },
          { label: "AI Document Generator", to: "/ai-document-generator", requiredPermissions: ["MANAGE_AI_DOCUMENT_GENERATOR"] },
          { label: "AI Generator List", to: "/ai-document-generator-list", requiredPermissions: ["VIEW_AI_GENERATOR_LIST"] },
          { label: "AI Prompt Templates", to: "/aiprompttemplate", requiredPermissions: ["MANAGE_AI_PROMPT_TEMPLATES"] },
          { label: "OCR Content Extractor", to: "/documents/ocr_content_extractor", requiredPermissions: ["MANAGE_OCR_CONTENT_EXTRACTOR"] },
          { label: "Bulk Document Upload", to: "/bulk-document-upload", requiredPermissions: ["MANAGE_BULK_DOCUMENT_UPLOAD"] },
          { label: "File Request Link", to: "/file-request", requiredPermissions: ["MANAGE_FILE_REQUEST_LINK"] },
          { label: "Documents Audit Trail", to: "/document-audit-trails", requiredPermissions: ["VIEW_DOCUMENT_AUDIT_TRAIL"] },
          { label: "Recent Activity", to: "/recent-activity", requiredPermissions: ["VIEW_RECENT_ACTIVITY"] },
          { label: "Archive Documents", to: "/archive-documents", requiredPermissions: ["VIEW_ARCHIVE_DOCUMENTS"] },
          { label: "Archive Folders", to: "/archive-folders", requiredPermissions: ["VIEW_ARCHIVE_FOLDERS"] },
          { label: "Archive Retention Period", to: "/archive-retention-period", requiredPermissions: ["MANAGE_ARCHIVE_RETENTION_PERIOD"] },
          { label: "Document Status", to: "/document-status", requiredPermissions: ["VIEW_DOCUMENT_STATUS"] },
        ],
      },
      {
        label: "Workflows",
        icon: RepeatIcon,
        requiredPermissions: ["MANAGE_WORKFLOW_SETTINGS"],
        children: [
          { label: "Workflow Setup Settings", to: "/workflow-settings", requiredPermissions: ["MANAGE_WORKFLOW_SETTINGS"] },
          { label: "All Workflows", to: "/workflows", requiredPermissions: ["VIEW_WORKFLOWS"] },
          { label: "Request Doc via Workflow", to: "/request_document_through_workflow", requiredPermissions: ["MANAGE_REQUEST_DOC_VIA_WORKFLOW"] },
          { label: "Workflow Logs", to: "/workflowlogs", requiredPermissions: ["VIEW_WORKFLOW_LOGS"] },
        ],
      },
      { label: "My Workflows", to: "/current-workflow", icon: MergeIcon, requiredPermissions: ["VIEW_MY_CHANGE_ACTIONS"] },
      { label: "Reminder", to: "/reminders", icon: BellIcon, requiredPermissions: ["VIEW_REMINDERS"] },
      { label: "Clients", to: "/client", icon: FolderSharedIcon, requiredPermissions: ["VIEW_CLIENTS"] },
      {
        label: "Access Control",
        icon: ShieldIcon,
        requiredPermissions: ["VIEW_ROLES"],
        children: [
          { label: "Roles", to: "/roles", requiredPermissions: ["VIEW_ROLES"] },
          { label: "Users", to: "/users", requiredPermissions: ["VIEW_USERS"] },
          { label: "Role User", to: "/roles/users", requiredPermissions: ["VIEW_ROLE_USER"] },
        ],
      },
      {
        label: "Settings",
        icon: SettingsIcon,
        requiredPermissions: ["VIEW_GENERAL_SETTINGS"],
        children: [
          { label: "Email SMTP Settings", to: "/settings/smtp", requiredPermissions: ["VIEW_SMTP_SETTINGS"] },
          { label: "General Settings", to: "/settings", requiredPermissions: ["VIEW_GENERAL_SETTINGS"] },
          { label: "Storage Settings", to: "/settings/storage", requiredPermissions: ["VIEW_STORAGE_SETTINGS"] },
          { label: "Company Profile", to: "/settings/company-profile", requiredPermissions: ["VIEW_COMPANY_PROFILE"] },
        ],
      },
      {
        label: "Logs",
        icon: ListIcon,
        requiredPermissions: ["VIEW_LOGIN_AUDITS"],
        children: [
          { label: "Login Audits", to: "/login-audit", requiredPermissions: ["VIEW_LOGIN_AUDITS"] },
          { label: "Error Logs", to: "/logs", requiredPermissions: ["VIEW_ERROR_LOGS"] },
        ],
      },
    ],
  },
];
